<div class="toco-row gut">
  <div class="toco-3-4">
    <h1><?= $data['page']['headline']; ?></h1>
    <?= $data['page']['html']; ?>
  </div>
  <div id="page-sidebar" class="toco-1-4">
    <h2>Support this project</h2>
    <p>
      This project is totally free and Open source. If you want to support this
      project please send a donation to a trust below.
    </p>
    <div class="donate-box">
      <p>
        <img class="donate-logo-img" id="tsavo-logo" src="/images/Tsavo-Web-logo.png" alt="Tsavo Trust logo">
        The <strong>Tsavo Trust</strong> <a target="_blank" href="https://tsavotrust.org">tsavotrust.org</a>,
        founded in 2013, is an action orientated, field-based,
        Kenyan not-for-profit conservation organisation that works to give
        the wildlife and people of Tsavo the right to a future.
      </p>
      <p class="donate-link-box">
        <a
          class="donate-link"
          target="_blank"
          href="https://tsavotrust.org"
          title="Link to Tsavo Trust website">Donate now</a>
      </p>

    </div>
    <div class="donate-box">
      <p>
        <img class="donate-logo-img" id="swt-logo" src="/images/dswt-logo.png" alt="Tsavo Trust logo">
        As one of Africa’s oldest wildlife charities and a leading conservation organisation,
        the <strong>Sheldrick Wildlife Trust (SWT)</strong>
        <a target="_blank" href="https://www.sheldrickwildlifetrust.org" title="link of Sheldrick Wildlife Trust">www.sheldrickwildlifetrust.org</a>, embraces all measures that complement
        the conservation, preservation and protection of wildlife.
      </p>
      <p class="donate-link-box">
        <a class="donate-link"
           target="_blank"
           href="https://www.sheldrickwildlifetrust.org/donate"
           title="Link to heldrick Wildlife Trust (SWT) website">Donate now</a>
      </p>
    </div>
  </div>
</div>
