<!DOCTYPE html>
<html lang="en">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="author" content="">
  <meta name="keywords" content="">
  <meta name="description" content="">
  <title><?= $data->metadata->title ?></title>
  <link rel="stylesheet" href="/css/normalize.css">
  <link rel="stylesheet" href="/css/toco-core.css">
  <!--<link rel="stylesheet" href="/css/dark.min.css">-->
  <link rel="stylesheet" href="/js/highlight/styles/stackoverflow-light.min.css">
  <link rel="stylesheet" href="/css/template.css?v=2">
  <link rel="stylesheet" href="/css/site.css?v=2">
  <link rel="stylesheet" href="/css/satao.css">
  <!--<script src="https://kit.fontawesome.com/da373cf37e.js" crossorigin="anonymous"></script>-->
</head>
<body>
  <div id="site-wrapper" class="toco-row">
    <div id="page-header" class="toco-1">
      <?php sesto_view_render($views, 'page_header', $data) ?>
    </div>
    <div id="page-main" class="toco-1">
      <?php sesto_view_render($views, 'page_main', $data, false) ?>
    </div>
    <div id="page-footer" class="toco-1">
      <?php sesto_view_render($views, 'page_footer', $data) ?>
    </div>
  </div>

  <script>
    function toggle_menu() {
      var main_menu = document.getElementById("main-menu");
      if (main_menu.className === "main-nav") {
        main_menu.className += " expand";
      } else {
        main_menu.className = "main-nav";
      }
    }
    window.addEventListener('change', toggle_menu);
  </script>
  <script src="/js/highlight.min.js"></script>
  <script>hljs.highlightAll();</script>

</body>
</html>
