<div class="toco-container">
  <div id="page-header-container" class="toco-row">
    <div class="toco-2-12">
      <img id="site-logo" src="/images/logo.png" alt="Fongo logo">
      <a href="javascript:void(0);" class="menu-icon" onclick="toggle_menu()">
      <img src="/images/hamburger.png" alt="Hamburger menu icon">
    </a>
    </div>
    <div class="toco-10-12">
      <nav id="main-menu" class="main-nav">
        <a href="/">Home</a>
        <a href="/docs/">Documentation</a>
        <a href="https://gitlab.com/adavanzo/satao">Download</a>
      </nav>
    </div>
  </div>

</div>