<div id="banner">
  <div class="toco-row">
    <div id="section-hero" class="toco-1">
      <h1 class="slogan">A different way to write and publish HTML</h1>
    </div>
  </div>
  <div id="section-hero-credits" class="toco-row gut">
    <div class="toco-1">
      <p>
        Photo by Pixabay from <a target="_blank" href="https://www.pexels.com/photo/group-of-elephants-on-walking-on-brown-road-during-daytime-50611/">Pexels</a>
      </p>
    </div>
  </div>
</div>
<div id="hero-2nd" class="toco-row">
  <div class="toco-1">
    <h2>Satao is a document format for publishing HTML documents</h2>
  </div>
</div>
<div id="-box" class="toco-row gut">
  <div class="highlights toco-1-3">
    <header><h3>Easy to learn</h3></header>
    <div>
      <p>
        Satao uses primarily HTML tags with similar syntax
      </p>
    </div>
  </div>
  <div class="highlights toco-1-3">
    <header><h3>Fast processing</h3></header>
    <div>
      <p>
        Documents can be processed very fast
      </p>
    </div>
  </div>
  <div class="highlights toco-1-3">
    <header><h3>Tiny memory footprint</h3></header>
    <div>
      <p>Simple, made with few PHP functions</p>
    </div>
  </div>
</div>